---Write a query to display user name and password. Password should be generated by concatenating first two characters of user name , length of the user name and last three numbers in the phone number and give an alias name as USER_PASSWORD. Sort the results based on the user name in descending order.

SELECT name, (SUBSTR(name,1,2) || LENGTH(name) || SUBSTR((phno), -3))
AS USER_PASSWORD
FROM USERS
ORDER BY name DESC;
-- SUBSTR(name,1,2) || LENGTH(name) || SUBSTR(name, length(name),-3)
